// src/pages/projects.tsx
import '../../styles/styles.css';
import Project1 from "../../assets/img/project1.jpg";

function Project() {
  return (
    <main className="main px-lg-5 px-0">
         <section className="projects d-flex justify-content-center align-items-center" id="projects">
              <div className="container">
                  <hr className="line" />
                  <h1 className="my-4">Projekty</h1>
                  <div className="row">
                      <div className="col-lg-6 d-flex flex-column align-items-start justify-content-center d-none d-lg-block">
                          <div className="project-image">
                            <img src={Project1} alt="projekt" />
                          </div>
                      </div>
                      <div className="col-lg-6">
                          <p className="project-overline text-lg-end text-start">Projekt</p>
                          <h2 className="project-title text-lg-end text-start">KubalekWeb</h2>
                          <p className="project-description text-lg-end text-start">
                              Witaj! Stworzyłem własne portfolio które stanowi wizualne
                              i funkcjonalne zaplecze do prezentacji moich umiejętności i projektów, zwracając uwagę na
                              estetykę i resposywność. Cały projekt został wykonany od zera przeze mnie.
                          </p>
                          <ul className="project-techs justify-content-lg-end justify-content-start">
                              <li className="me-3">HTML</li>
                              <li className="me-3">CSS</li>
                              <li className="me-3">Bootstrap</li>
                              <li>React</li>
                          </ul>
                          <p className="project-link justify-content-lg-end justify-content-start">
                                <a href="https://github.com/Kubaleek/portfolio" target='_blank' aria-label="Link to Github">
                                    <i className="bi bi-github"></i>
                                </a>
                              <a href="https://kubaleek.github.io/portfolio/" className="ms-3" aria-label="Link to Portfolio">
                                  <i className="bi bi-box-arrow-up-right"></i>
                              </a>
                          </p>
                      </div>
                  </div>
              </div>
          </section>
    </main>
  );
}

export default Project

// src/app/projects/projects.component.ts
import { CommonModule } from '@angular/common';
import { Component} from '@angular/core';
import { NgxSplideModule } from 'ngx-splide';
@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, NgxSplideModule],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.css'
})
export class ProjectsComponent{
    ViewProject: string | null = null;
    // Funkcja Pokażania Szczegołówych informacji o projekcie
    ViewOnProject(project: string): void {
      this.ViewProject = project;
    }
    // Funkcja Ukrycia Szczegołówych informacji o projekcie
    ViewOffProject(): void{
      this.ViewProject = null;
    }
}

<section class="project section justify-content-center align-items-center h-50 w-100 pt-6 px-10 position-relative" id="project">
    <div class="container d-flex justify-content-center align-items-center">
        <div class="row justify-content-center align-items-center gx-5">
            <ng-container *ngTemplateOutlet="project1"></ng-container>
            <ng-template #project1>
              <div class="col-lg-6 col-md-9 col-sm-10 px-16 py-12 justify-content-center align-items-center">
                <splide>
                  <splide-slide>
                    <img src="assets/images/1.png" class="img-fluid project_img mb-3" alt="vector strona">
                  </splide-slide>
                  <splide-slide>
                    <img src="assets/images/1.1.png" class="img-fluid project_img mb-3" alt="vector strona">
                  </splide-slide>
                  <splide-slide>
                    <img src="assets/images/2.png" class="img-fluid project_img mb-3" alt="vector strona">
                  </splide-slide>
                  <splide-slide>
                    <img src="assets/images/3.png" class="img-fluid project_img mb-3" alt="vector strona">
                  </splide-slide>
                </splide>
              </div>
            </ng-template>
            <div *ngIf="!ViewProject" class="col-lg-12 col-md-9 col-sm-10 px-16 py-12 justify-content-center align-items-center order-2 order-lg-0 mt-5" >
                <p class="portfolio_l text-center">
                    <a href="https://github.com/Kubaleek/portfolio"><i class="bi bi-github"></i></a>
                    <a><i class="bi bi-box-arrow-in-up-right pm" (click)="ViewOnProject('Portfolio')"></i></a>
                </p>
                <hr class="project_line my-4 mx-auto hr w-25">
            </div>     
            <!-- Wyświetlanie informacji o projekcie --> 
            <div *ngIf="ViewProject" class="col-lg-7 col-md-10 col-sm-10 px-16 py-12 justify-content-center align-items-center portfolio_box">
                <!-- Informacje o wybranym projekcie -->
                <h1 class="text-center">{{ ViewProject }}</h1>
                <div class="projects_i align-items-center justify-content-center">
                    <p class="portfolio_p text-center mt-5 mb-5">
                        Witaj! Stworzyłem mój pierwszy własny projekt portfolio które stanowi wizualne 
                        i funkcjonalne zaplecze do prezentacji moich umiejętności i projektów. 
                    </p>
                    <p class="project_text2 text-center mt-5 mb-5">
                        Angular, HTML, CSS, Typescript
                    </p>
                    <p class="project_text project_text_tech mt-5 text-center project_tech d-none d-md-block">
                        <i class='bx bxl-html5'></i>
                        <i class='bx bxl-css3'></i>
                        <i class='bx bxl-angular'></i>
                        <i class='bx bxl-typescript'></i>
                    </p>
                </div>
                <div class="projects_b d-flex align-items-center justify-content-center mt-5 mb-5" >
                    <button class="cssbuttons-io-button btn text-center" (click)="ViewOffProject()">Projekty
                        <div class="icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
                              </svg>
                        </div>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
